services:

  mandat-app-auth:
    build:
      context: ./apps/auth
      dockerfile: ../../Dockerfile-app
    ports:
      - "8084:80"

  mandat-app-bank:
    build:
      context: ./apps/bank
      dockerfile: ../../Dockerfile-app
    ports:
      - "8081:80"

  mandat-app-tao:
    build:
      context: ./apps/tao
      dockerfile: ../../Dockerfile-app
    ports:
      - "8082:80"

  mandat-app-sme:
    build:
      context: ./apps/sme
      dockerfile: ../../Dockerfile-app
    ports:
      - "8083:80"

  mandat-lib-components:
    build:
      context: ./libs/components
      dockerfile: ../../Dockerfile-lib

  mandat-lib-composables:
    build:
      context: ./libs/composables
      dockerfile: ../../Dockerfile-lib

  mandat-lib-solid-interop:
    build:
      context: ./libs/solid-interop
      dockerfile: ../../Dockerfile-lib

  mandat-lib-solid-oidc:
    build:
      context: ./libs/solid-oidc
      dockerfile: ../../Dockerfile-lib

  mandat-lib-solid-requests:
    build:
      context: ./libs/solid-requests
      dockerfile: ../../Dockerfile-lib

  mandat-lib-theme:
    build:
      context: ./libs/theme
      dockerfile: ../../Dockerfile-lib

  mandat-lib-utils:
    build:
      context: ./libs/utils
      dockerfile: ../../Dockerfile-lib
