services:

  mandat-app-auth:
    build:
      context: ./apps/auth
      dockerfile: ../../Dockerfile-app
    ports:
      - "8084:80"

  mandat-app-bank:
    build:
      context: ./apps/bank
      dockerfile: ../../Dockerfile-app
    ports:
      - "8081:80"

  mandat-app-tao:
    build:
      context: ./apps/tao
      dockerfile: ../../Dockerfile-app
    ports:
      - "8082:80"

  mandat-app-sme:
    build:
      context: ./apps/sme
      dockerfile: ../../Dockerfile-app
    ports:
      - "8083:80"